import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footer, Header } from "../site-components";

const pageInfo = {
  "chi-siamo": { kicker: "Chi siamo", title: "Lo studio legale AI-first.", intro: "Un modello operativo che integra competenza, metodo e tecnologia per aumentare la qualità del lavoro legale.", next: ["Metodo", "/metodo"] },
  metodo: { kicker: "Il nostro metodo", title: "Dalla conoscenza alla decisione.", intro: "Una pipeline specializzata per ogni mandato, governata dagli avvocati e migliorata nel tempo.", next: ["Competenze", "/competenze"] },
  competenze: { kicker: "Competenze", title: "Diritto corporate, aumentato.", intro: "Assistenza qualificata e continuativa per imprese, management, fondi e realtà in trasformazione.", next: ["Case Studies", "/case-studies"] },
  "case-studies": { kicker: "Case Studies", title: "Il metodo, nella pratica.", intro: "Casi selezionati per mostrare come competenza legale, processi e AI cambiano concretamente il lavoro.", next: ["Team", "/team"] },
  "case-study": { kicker: "Caso dimostrativo · contenuto provvisorio", title: "Due diligence aumentata.", intro: "Un esempio anonimo per mostrare come il modello Vectis può trasformare una due diligence in un processo più leggibile, verificabile e orientato alla decisione.", next: ["Case Studies", "/case-studies"] },
  team: { kicker: "Il team", title: "Le persone dietro il giudizio.", intro: "Esperienza professionale, responsabilità diretta e una cultura costruita per l’evoluzione del lavoro legale.", next: ["Chi siamo", "/chi-siamo"] },
} as const;

const values = [["01","AI come metodo","La tecnologia è parte strutturale del lavoro, mai un fine in sé."],["02","Human-led judgment","Strategia, supervisione e responsabilità restano sempre umane."],["03","Valore, non volume","Misuriamo la solidità delle decisioni, non le ore impiegate."],["04","Tempestività","Risposte rapide senza sacrificare accuratezza e profondità."]];
const process = [["01","Expert judgment","Il partner e il team legale analizzano esigenze, obiettivi e natura del lavoro."],["02","AI workflow","I Legal AI Specialist costruiscono una pipeline dedicata alle specificità del mandato."],["03","Knowledge","Il sistema recupera storico cliente, precedenti di studio e ricerca legale rilevante."],["04","Quality review","Gli avvocati verificano l’output secondo la metodologia Vectis, con responsabilità diretta."],["05","Feedback loop","Ogni revisione arricchisce il sistema e rende più profonda la conoscenza del cliente."]];
const expertise = [
  {n:"01",title:"Operazioni straordinarie",subtitle:"Decisioni complesse, informazioni leggibili.",doing:"M&A / Due diligence / Riorganizzazioni societarie / Joint venture / Operazioni sul capitale",change:"Costruiamo una pipeline dedicata che organizza documenti, anomalie e rischi, collega le evidenze e mantiene la revisione professionale al centro. La due diligence diventa una base di conoscenza strutturata, non una semplice raccolta di risultati.",caseTitle:"Due diligence aumentata",caseId:"01"},
  {n:"02",title:"Diritto societario e compliance",subtitle:"Governance solida, controllo continuativo.",doing:"Corporate governance / Segreteria societaria / Controlli interni / Modelli organizzativi / Compliance integrata",change:"La conoscenza societaria viene organizzata e aggiornata nel tempo. Workflow e controlli rendono verificabili responsabilità, adempimenti e passaggi decisionali, riducendo frammentazione e attività ripetitive.",caseTitle:"Compliance continua",caseId:"02"},
  {n:"03",title:"Contrattualistica commerciale",subtitle:"Relazioni più chiare, negoziazioni più consapevoli.",doing:"Drafting / Revisione contrattuale / Negoziazione / Standardizzazione / Gestione del patrimonio contrattuale",change:"Il modello Vectis confronta clausole, precedenti e posizioni negoziali, facendo emergere ricorrenze e rischi. L’avvocato conserva la regia e concentra il proprio tempo sulle scelte che incidono davvero sulla relazione.",caseTitle:"Contratti sotto controllo",caseId:"03"},
  {n:"04",title:"Normativa AI",subtitle:"Innovare dentro un perimetro affidabile.",doing:"AI Act / Governance AI / Risk assessment / Policy interne / Responsabilità e conformità",change:"Traduciamo la regolazione in un sistema operativo: ruoli, controlli, evidenze e aggiornamenti. La conformità accompagna l’adozione dell’AI senza diventare un passaggio isolato o puramente documentale.",caseTitle:"Governance AI by design",caseId:"04"},
  {n:"05",title:"Managed Legal Services",subtitle:"Il presidio legale diventa capacità operativa.",doing:"Legal operations / Supporto continuativo / Workflow dedicati / Reporting / Knowledge management",change:"Processi ripetibili, dati e conoscenza del cliente vengono integrati in un presidio su misura. Tempi, responsabilità e costi diventano più leggibili e prevedibili.",caseTitle:"Legal operations integrate",caseId:"05"},
  {n:"06",title:"Regulatory Monitoring",subtitle:"Dalla rincorsa alla prevenzione.",doing:"Mappatura normativa / Monitoraggio degli sviluppi / Scadenziario / Impatti operativi / Reporting",change:"Fonti, obblighi e scadenze vengono ordinati in un flusso continuo. Gli aggiornamenti rilevanti arrivano già contestualizzati, pronti per una valutazione legale e una decisione operativa.",caseTitle:"Regulatory radar",caseId:"06"},
];

const cases = [
  ["01","Due diligence aumentata","M&A · Legal intelligence","Trasformare migliaia di documenti in evidenze verificabili e decisioni più rapide."],
  ["02","Compliance continua","Governance · Regulatory monitoring","Un presidio che connette norme, responsabilità, scadenze e azioni correttive."],
  ["03","Contratti sotto controllo","Commercial · Managed legal services","Rendere leggibile il patrimonio contrattuale per negoziare e decidere meglio."],
  ["04","Governance AI by design","AI regulation · Compliance","Portare l’AI nei processi aziendali con ruoli, verifiche ed evidenze chiare."],
  ["05","Legal operations integrate","Managed legal services","Integrare assistenza professionale, processi e conoscenza in un unico presidio."],
  ["06","Regulatory radar","Regulatory monitoring","Anticipare gli impatti normativi e trasformarli in attività governabili."],
];

function AboutOpening() { return <section className="aboutOpening internalSection"><div className="wrap internalSplit"><h2>Un modello costruito<br /><em>da zero.</em></h2><p className="bigCopy">Vectis nasce dall’incontro tra esperienza legale, progettazione dei processi e competenze AI, con l’obiettivo di ripensare il modo in cui il lavoro legale viene prodotto, verificato e gestito.</p></div></section>; }

function AboutPage() { return <>
  <section className="internalEditorial internalSection wrap"><p className="consultingKicker">Il nostro modello</p><div className="internalSplit"><h2>L’intelligenza artificiale non sostituisce il giudizio.<br /><em>Lo amplifica.</em></h2><div><p className="bigCopy">Vectis nasce per riprogettare il lavoro legale attorno a ciò che crea davvero valore: decisioni migliori.</p><p>Automatizziamo in modo strutturato le attività scalabili, organizziamo la conoscenza e costruiamo processi dedicati a ogni mandato. Il tempo liberato torna dove conta: analisi, strategia, controllo e responsabilità.</p></div></div></section>
  <section className="principlesBlock internalSection"><div className="wrap"><div className="centerHeading"><p className="consultingKicker inverse">I nostri valori</p><h2>Un nuovo modo<br />di esercitare il diritto.</h2></div><div className="principleGrid">{values.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="internalQuote internalSection wrap"><p>“L’efficienza è una conseguenza del metodo, non l’obiettivo.”</p><span>Vectis Legal</span></section>
</>; }

function MethodPage() { return <>
  <section className="processIntro internalSection wrap"><p className="consultingKicker">Come lavoriamo</p><h2>Più conoscenza.<br />Più controllo.<br /><em>Più giudizio.</em></h2></section>
  <section className="processRows wrap">{process.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</section>
  <section className="methodOutcome internalSection"><div className="wrap internalSplit"><h2>Velocità<br /><em>senza fretta.</em></h2><div><p className="bigCopy">Ogni passaggio aumenta la profondità del successivo.</p><p>La tecnologia accelera la ricerca. Il workflow preserva continuità e tracciabilità. La quality review trasforma il risultato in una decisione professionale affidabile.</p></div></div></section>
</>; }

function ExpertisePage() { return <>
  <section className="expertiseIntro internalSection wrap"><p className="consultingKicker">Aree di attività</p><div className="internalSplit"><h2>Per il mondo<br /><em>corporate.</em></h2><p className="bigCopy">Affianchiamo imprese e management nelle decisioni che richiedono velocità, controllo e una lettura completa del rischio.</p></div></section>
  <section className="expertiseAccordion">{expertise.map((item,i)=><details name="expertise" className="expertiseRow" key={item.n} open={i===0}><summary><span>{item.n}</span><div><h3>{item.title}</h3><p>{item.subtitle}</p></div><b aria-hidden="true">+</b></summary><div className="expertiseExpanded"><div><span>Cosa facciamo</span><p>{item.doing}</p></div><div><span>Come cambia con Vectis</span><p>{item.change}</p></div><div><span>Selected case</span><a href="/case-study">{item.caseTitle} <b>→</b></a></div></div></details>)}</section>
  <section className="managedBand internalSection"><div className="wrap"><p className="consultingKicker inverse">Presidio continuativo</p><h2>Assistenza professionale<br />e capacità operativa.</h2><p>Managed Legal Services e Regulatory Monitoring trasformano la consulenza in un sistema continuativo, personalizzato e prevedibile.</p></div></section>
</>; }

function CasesPage() { return <><section className="casesIntro internalSection wrap"><p className="consultingKicker">Selected work</p><div className="internalSplit"><h2>Problemi reali.<br /><em>Sistemi dedicati.</em></h2><p className="bigCopy">Non mostriamo soltanto il risultato: raccontiamo come il modello Vectis modifica il processo che porta alla decisione.</p></div></section><section className="casesIndex">{cases.map(([n,t,k,d])=><article id={`case-${n}`} key={n}><a href="/case-study" className="wrap caseIndexRow"><span>{n}</span><div><p>{k}</p><h3>{t}</h3></div><p>{d}</p><b>↗</b></a></article>)}</section></>; }

function CaseStudyPage() { return <><section className="caseFacts internalSection"><div className="wrap"><p className="consultingKicker">Scheda del caso</p><div className="caseFactsGrid"><div><span>Ambito</span><strong>M&A / Due diligence</strong></div><div><span>Contesto</span><strong>Operazione cross-border</strong></div><div><span>Modello</span><strong>Workflow AI human-led</strong></div><div><span>Stato</span><strong>Concept dimostrativo</strong></div></div></div></section><section className="caseNarrative internalSection wrap"><div className="caseChapter"><span>01 · La sfida</span><h2>Molti documenti.<br />Poco tempo per decidere.</h2><div><p className="bigCopy">Un’impresa deve valutare un’acquisizione con una data room ampia, fonti eterogenee e tempi compressi.</p><p>Il rischio non consiste soltanto nel non trovare un’informazione, ma nel perdere le relazioni tra documenti, clausole, anomalie e priorità dell’operazione.</p></div></div><div className="caseChapter"><span>02 · Cosa cambia</span><h2>La due diligence diventa un sistema di conoscenza.</h2><div><p className="bigCopy">Vectis costruisce una pipeline dedicata al mandato, invece di applicare uno strumento generico alla documentazione.</p><p>La tecnologia organizza e collega le evidenze. Il team legale definisce criteri, verifica gli output, interpreta il contesto e mantiene la responsabilità professionale.</p></div></div></section><section className="caseWorkflow internalSection"><div className="wrap"><p className="consultingKicker inverse">Il processo</p><div className="caseWorkflowGrid">{[["01","Scope","Obiettivi, soglie di materialità e aree di rischio."],["02","Ingestion","Documenti classificati e collegati alla struttura dell’operazione."],["03","Analysis","Evidenze, anomalie e ricorrenze rese interrogabili."],["04","Review","Verifica legale, contestualizzazione e controllo qualità."],["05","Decision","Risultati sintetizzati in una lettura operativa del rischio."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section><section className="caseOutcome internalSection wrap"><p className="consultingKicker">Il risultato atteso</p><div className="internalSplit"><h2>Più copertura.<br />Più tracciabilità.<br />Più giudizio.</h2><div><p className="bigCopy">Il valore non è una due diligence semplicemente più veloce.</p><p>È una base decisionale più solida: ogni rilievo resta collegato alle fonti, le priorità sono leggibili e la conoscenza prodotta può continuare a essere utilizzata dopo il closing.</p><a className="underLink" href="/case-studies">Torna ai Case Studies <span>←</span></a></div></div><p className="caseDisclaimer">Contenuto dimostrativo per la validazione dell’architettura del sito. Non descrive un cliente o un incarico reale.</p></section></>; }

function TeamPage() { return <>
  <section className="teamIntro internalSection wrap"><p className="consultingKicker">Leadership</p><h2>Il giudizio è umano.<br /><em>La capacità è aumentata.</em></h2></section>
  <section className="consultantTeam wrap"><article><div className="consultantPortrait portraitOne"><span>AM</span></div><p>Fondatore & Managing Partner</p><h3>Alessandro Musella</h3><a href="mailto:musella@vectislegal.eu">Contatta ↗</a></article><article><div className="consultantPortrait portraitTwo"><span>MG</span></div><p>Fondatore e Presidente Esecutivo</p><h3>Mauro Gigante</h3></article></section>
  <section className="teamCulture internalSection"><div className="wrap internalSplit"><h2>Competenze diverse.<br /><em>Un unico processo.</em></h2><div><p className="bigCopy">Team legali e specialisti AI lavorano fianco a fianco.</p><p>Ciascuno porta la propria competenza, mentre strategia, supervisione e responsabilità professionale guidano ogni decisione.</p></div></div></section>
</>; }

export function generateStaticParams() { return Object.keys(pageInfo).map(slug => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{slug:string}> }): Promise<Metadata> { const {slug}=await params; const page=pageInfo[slug as keyof typeof pageInfo]; if(!page) return {}; return { title: page.title, description: page.intro, openGraph:{title:`${page.title} | Vectis`,description:page.intro,images:[]},twitter:{title:`${page.title} | Vectis`,description:page.intro,images:[]}}; }

export default async function DetailPage({ params }: { params: Promise<{slug:string}> }) {
  const { slug } = await params; const page = pageInfo[slug as keyof typeof pageInfo]; if (!page) notFound();
  return <main className="consultingInternal"><section className="internalConsultingHero"><Header dark={false}/><div className="wrap"><p className="consultingKicker">{page.kicker}</p><h1>{page.title}</h1><p>{page.intro}</p></div></section>{slug==="chi-siamo"?<AboutOpening/>:null}{slug==="chi-siamo"?<AboutPage/>:slug==="metodo"?<MethodPage/>:slug==="competenze"?<ExpertisePage/>:slug==="case-studies"?<CasesPage/>:slug==="case-study"?<CaseStudyPage/>:<TeamPage/>}<Footer/></main>;
}
